image: didstopia/msbuild:latest
stages:
  - build

before_script:
  - nuget restore

build:
 stage: build
 script:
  - msbuild.exe SpotifyPlaylistMixer.sln /t:ReBuild /p:Configuration=Release;Platform="Any CPU" /tv:14.0 /p:TargetFrameworkVersion=v4.6.2